version: "3.9"

services:
  app:
    image: python:3.10
    container_name: fastapi-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=fastapi_user
      - MYSQL_PASSWORD=fastapi_password
      - MYSQL_DB=fastapi_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
      MYSQL_DATABASE: fastapi_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: